services:
  signage:
    image: tjay466/sign:latest
    container_name: signage_display
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
    restart: always
    environment:
      - NODE_ENV=production
